"""upgrade

Revision ID: 01c7c0ce0d69
Revises: 0b51af19e91c
Create Date: 2025-03-06 08:53:01.283334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c7c0ce0d69'
down_revision = '0b51af19e91c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.drop_column('approved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
