"""Updated Charity model with verification details

Revision ID: 0d9b3bd15b40
Revises: 6f2ccc5c9493
Create Date: 2025-03-02 20:48:44.651483
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0d9b3bd15b40'
down_revision = '6f2ccc5c9493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_number', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('account_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('account_holder', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('targeted_amount', sa.Float(), nullable=False))
        
        # Explicitly name the unique constraints
        batch_op.create_unique_constraint('uq_account_number', ['account_number'])
        batch_op.create_unique_constraint('uq_email', ['email'])
        batch_op.create_unique_constraint('uq_registration_number', ['registration_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.drop_constraint('uq_registration_number', type_='unique')
        batch_op.drop_constraint('uq_email', type_='unique')
        batch_op.drop_constraint('uq_account_number', type_='unique')
        
        batch_op.drop_column('targeted_amount')
        batch_op.drop_column('account_holder')
        batch_op.drop_column('account_number')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('registration_number')

    # ### end Alembic commands ###
