"""Updated Charity model - removed registration number, made bank details optional, phone number required

Revision ID: 280cf05a1eca
Revises: 0d9b3bd15b40
Create Date: 2025-03-02 20:59:03.083492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280cf05a1eca'
down_revision = '0d9b3bd15b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=False))
        batch_op.alter_column('bank_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('account_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('account_holder',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_constraint('uq_registration_number', type_='unique')
        batch_op.drop_column('registration_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_number', sa.VARCHAR(length=255), nullable=False))
        batch_op.create_unique_constraint('uq_registration_number', ['registration_number'])
        batch_op.alter_column('account_holder',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('account_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('bank_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
