"""added a to dict

Revision ID: 33a3e73bcf14
Revises: 933a1351e785
Create Date: 2025-03-05 17:41:24.913097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a3e73bcf14'
down_revision = '933a1351e785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paypal_order_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payer_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['donation_id'], ['donation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('donation_id'),
    sa.UniqueConstraint('paypal_order_id')
    )
    op.drop_table('transaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('paypal_order_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), nullable=False),
    sa.Column('payer_email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('donation_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['donation_id'], ['donation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('donation_id'),
    sa.UniqueConstraint('paypal_order_id')
    )
    op.drop_table('transactions')
    # ### end Alembic commands ###
