"""upgrade phone number to false 

Revision ID: 51973a320b8f
Revises: 01c7c0ce0d69
Create Date: 2025-03-06 08:56:12.410151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51973a320b8f'
down_revision = '01c7c0ce0d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
