""" nullable is true

Revision ID: 590499cf1d1f
Revises: c4fd1d35a3e0
Create Date: 2025-03-05 10:23:15.068740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590499cf1d1f'
down_revision = 'c4fd1d35a3e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('targeted_amount',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.alter_column('targeted_amount',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
