<<<<<<<< HEAD:backend/migrations/versions/e566b200500a_initial_migrations.py
"""initial migrations

Revision ID: e566b200500a
Revises: 
Create Date: 2025-03-02 22:56:15.340748
========
"""Initial re-migration

Revision ID: 6f2ccc5c9493
Revises: 
Create Date: 2025-03-02 17:36:29.948740
>>>>>>>> bd9c2ff393d1854988923e6a205c6714511a1f91:backend/migrations/versions/6f2ccc5c9493_initial_re_migration.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:backend/migrations/versions/e566b200500a_initial_migrations.py
revision = 'e566b200500a'
========
revision = '6f2ccc5c9493'
>>>>>>>> bd9c2ff393d1854988923e6a205c6714511a1f91:backend/migrations/versions/6f2ccc5c9493_initial_re_migration.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('profile_picture', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.CheckConstraint("role IN ('user', 'admin', 'charity')", name='valid_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('charities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('charity_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('password', sa.String(length=512), nullable=False),
<<<<<<<< HEAD:backend/migrations/versions/e566b200500a_initial_migrations.py
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=False),
========
    sa.Column('profile_picture', sa.String(length=1024), nullable=False),
    sa.Column('approved', sa.String(length=20), nullable=True),
>>>>>>>> bd9c2ff393d1854988923e6a205c6714511a1f91:backend/migrations/versions/6f2ccc5c9493_initial_re_migration.py
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('charity_name')
    )
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('donation_date', sa.DateTime(), nullable=False),
    sa.Column('donation_type', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paypal_order_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payer_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['donation_id'], ['donation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('donation_id'),
    sa.UniqueConstraint('paypal_order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('donation')
    op.drop_table('stories')
    op.drop_table('charities')
    op.drop_table('users')
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
