"""added approved column in charity table

Revision ID: 96618e58757a
Revises: b9ff8bfd3e04
Create Date: 2025-02-26 13:15:14.267786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96618e58757a'
down_revision = 'b9ff8bfd3e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
