"""Fixing migration mismatch

Revision ID: b9ff8bfd3e04
Revises: 11e725d09034
Create Date: 2025-02-26 12:25:05.092630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ff8bfd3e04'
down_revision = '11e725d09034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
