"""removed the test column

Revision ID: ba164d4df1a7
Revises: 77274ced55f7
Create Date: 2025-02-25 10:41:31.268423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba164d4df1a7'
down_revision = '77274ced55f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('test_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_column', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
